<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\MSBuild\Robust.Engine.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\Server3D</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Robust.Shared3D\Robust.Shared3D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Robust.Shared3D\Worlds\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <Import Project="..\MSBuild\Robust.Properties.targets" />
</Project>
