<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\MSBuild\Robust.Engine.props" />
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Robust.Shared3D\Robust.Shared3D.csproj" />
    <ProjectReference Include="..\Robust.Server3D\Robust.Server3D.csproj" />
    <ProjectReference Include="..\Robust.Client3D\Robust.Client3D.csproj" />
  </ItemGroup>
</Project>
