<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\MSBuild\Robust.Engine.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>Robust.Client3D.Client3DEntryPoint</StartupObject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\Client3D</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenToolkit.Graphics" />
    <PackageReference Include="SpaceWizards.Sdl" />
    <PackageReference Include="Robust.Natives" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Robust.Shared.Maths\Robust.Shared.Maths.csproj" />
    <ProjectReference Include="..\Robust.Shared3D\Robust.Shared3D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Models\**\*.gltf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Assets\Models\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="Assets\Models\**\*.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Assets\Models\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="..\Robust.Shared3D\Worlds\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <Import Project="..\MSBuild\Robust.Properties.targets" />
</Project>
