<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\MSBuild\Robust.Engine.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Robust.Client3D</RootNamespace>
    <OutputPath>../bin/Client3D</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Robust.Shared3D\Robust.Shared3D.csproj" />
  </ItemGroup>
</Project>
